### ISSUE TITLE
Message Fields list sort issue. 

### ISSUE THREAD

**Issue by sgundeti** [guilhemmarchand/TA-ms-teams-alert-action#17]
By Default Message fields list are sorted in alphabetical order in message card. It would nice if we can control the order of fields displayed in card. for example use the same order as mentioned in “Message fields list”. 
Below is screenshot of card with fields sorted in alphabetical order. 
![image](https://user-images.githubusercontent.com/6694116/81122010-4eb66580-8f30-11ea-8772-accdb7e995d7.png)

**Comment by guilhemmarchand** [comment]
@sgundeti 
Addressed by version 1.0.13 which is now published in Splunk Base.
