### ISSUE TITLE
Only first row of table is posted

### ISSUE THREAD

**Issue by gowtham495** [guilhemmarchand/TA-ms-teams-alert-action#18]
When I try to post a table Splunk result to MS Teams, only the data of the first row is getting published. Is there any way to get the whole table published in table format itself.

**Comment by guilhemmarchand** [comment]
@gowtham495 

How do you post the results from the table ? Is it a scheduled alert with the MS Teams alert action enabled ?

Are you using the very last version of the app too ?

By default each row of a table should result in a message generated in MS Teams, one way as well if to make sure you edit the alert in the alert editor and select "For each results" instead of the default "Once"

Please share screenshots if you have.

**Comment by gowtham495** [comment]
Thanks for reverting back.

Yes, it is an scheduled alert, which has 3 columns ( jobName, endTime, status) and 10 rows.

Using latest version of app. Installed last week only.

Unfortunately i could not take screenshot, but i replicated the error in a snapshot.

I wanted a summarized table to get published in Teams, so "For Each Results" will not work

Thanks in advance

![err](https://user-images.githubusercontent.com/35063768/81553470-bc381b00-93a2-11ea-9e52-204484ce8a11.PNG)

**Comment by guilhemmarchand** [comment]
Right, let me check this, the Addon is not designed to produce a table in a field value.

**Comment by gowtham495** [comment]
Any workaround you know to publish results in table format will be much helpful for me.

**Comment by guilhemmarchand** [comment]
@gowtham495  You could tried this @gowtham495 and see MS Teams recognise the new line (\n):

```
| makeresults
| eval jobName="Job A", endTime="20:00", status="SUCCESS"
| append [ | makeresults
| eval jobName="Job B", endTime="19:30", status="FAILURE" ]
| append [ | makeresults
| eval jobName="Job C", endTime="23:45", status="FAILURE" ]
| fields - _time

| eval job_summary = "jobName: " . jobName . " | endTime: " . endTime . " | status: " . status . ","
| fields job_summary
| eval AAA=split(job_summary, "\n")
| eventstats values(AAA) as job_summary| fields job_summary
| head 1
| mvcombine delim="," job_summary
| rex field=job_summary mode=sed "s/,$//g"
| rex field=job_summary mode=sed "s/, /\n/g"
```

Basically creating a single value field which looks a table, let me know how this looks like in teams, the first part with makeresults is just to simulate your input

**Comment by gowtham495** [comment]
I'm getting output like 

jobName: Job A | endTime: 20:00 | status=SUCCESS jobName: Job B | endTime: 19:30 | status=FAILURE jobName: Job A | endTime: 23:45 | status=FAILURE


All in single line, not formatted as table.

**Comment by guilhemmarchand** [comment]
Right I see ;-)

What if you try:

```
| makeresults
| eval jobName="Job A", endTime="20:00", status="SUCCESS"
| append [ | makeresults
| eval jobName="Job B", endTime="19:30", status="FAILURE" ]
| append [ | makeresults
| eval jobName="Job C", endTime="23:45", status="FAILURE" ]
| fields - _time
| eval job_summary = "jobName: " . jobName . " | endTime: " . endTime . " | status: " . status . "<br />"
| fields job_summary
| eval AAA=split(job_summary, "\n")
| eventstats values(AAA) as job_summary| fields job_summary
| head 1
| mvcombine delim="," job_summary
| rex field=job_summary mode=sed "s/,$//g"
| rex field=job_summary mode=sed "s/, /\n/g"
```

I might need to double check because as far as I remember, the markdown language is disabled on purpose, but I could make this a selectable option.

**Comment by gowtham495** [comment]
Great ! It Worked ! Thanks a lot :) 
Now the output are like - 

jobName: Job A | endTime: 20:00 | status=SUCCESS 
jobName: Job B | endTime: 19:30 | status=FAILURE 
jobName: Job A | endTime: 23:45 | status=FAILURE

May I know what happened ?

**Comment by guilhemmarchand** [comment]
Yeah !

Sure, MS Teams understands markdown and html, the "\n" which the backends on the addon side is not understood by Teams as a new line.

Therefore `<br />` is interpreted properly as new line.

I will put this in the documentation how on a page to handle similar mvfields.

Let me know if you have any other question, and if not/ if you are happy with this issue feel free to close the issue

**Comment by gowtham495** [comment]
Once again.. Thank you very much for your time in resolving this issue.
