### ISSUE TITLE
Proxy trouble

### ISSUE THREAD

**Issue by juanjon1** [guilhemmarchand/TA-ms-teams-alert-action#19]
Hello,

We are having some problems configuring the proxy in the Add-On.
If there is no proxy on our network, how can we set it? localhost:80?

Thank you.

**Comment by guilhemmarchand** [comment]
Hi @juanjon1 

Proxy settings are optionals and you would use them only if mandatory need to use one because your constraints impose it.

If you don't to have to, just don't enable it.

Let me know if it makes sense.

**Comment by guilhemmarchand** [comment]
Close due to lack activity, proxy settings are taken in charge by the app.
