### ISSUE TITLE
Ignore ssl verification.

### ISSUE THREAD

**Issue by atilaloise** [guilhemmarchand/TA-ms-teams-alert-action#20]
In environments with ssl interception there is an error of SSL: CERTIFICATE_VERIFY_FAILED

Is ther a workaround or the possibility to include this configuration?

Congrats for this project and thanks!

**Comment by guilhemmarchand** [comment]
Hi @atilaloise 

Thanks for reporting, I will add an option in the settings to allow disabling SSL verification. (has to be enabled by default for Splunk Cloud vetting purposes)

Guilhem

**Comment by guilhemmarchand** [comment]
@atilaloise 

Addressed by version 1.0.13 which is now published in Splunk Base.
