### ISSUE TITLE
ensure aob configuration replicates in shc environment

### ISSUE THREAD

**Issue by crumpetcrusher** [guilhemmarchand/TA-ms-teams-alert-action#26]
AOB apps don't seem to have a default entry for the custom conf file they create.  This will ensure the cluster replicates the settings to every member.

add server.conf in default folder with the following stanza and property:
```
[shclustering]
conf_replication_include.ta_ms_teams_alert_action_settings = true
```

**Comment by guilhemmarchand** [comment]
Thank you very much @crumpetcrusher 
I truly didn't realise the config was not synchronised automatically in a SHC context and trusted AoB was doing it right automatically, I definitvely tested earlier but didn't think in checking on different members explicitely.

So a new release, 1.0.17, was published and includes this fix.

Guilhem

**Comment by crumpetcrusher** [comment]
@guilhemmarchand you're very welcome, glad to help and thanks for the quick fix too!  It's caught me off guard a couple times now. 😅

Also, sorry, still getting the hang of collaboration here, didn't think at the time about making a pull request.
