### ISSUE TITLE
Theme Color as configurable option

### ISSUE THREAD

**Issue by chadjefferies** [guilhemmarchand/TA-ms-teams-alert-action#28]
We are thinking of switching over to this alert action from another less feature rich Teams connector. This connector appears much more configurable, however one thing that appears missing here is the ability to customize the themeColor on the MessageCard. This is important to us to indicate the type of alert being sent (e.g. red = something is broken, yellow is a warning, green is OK) Is that something you'd be open to adding as a configurable option? 

Thanks!

**Comment by guilhemmarchand** [comment]
Hi @chadjefferies 

Sure thing, this shouldn't be an issue to integrate this option.

From Microsoft docs:
https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

I believe the option would be:

themeColor | String | Specifies a custom brand color for the card. The color will be displayed in a non-obtrusive manner.Do use themeColor to brand cards to your color.Don't use themeColor to indicate status.
-- | -- | --

I will have a look shortly, would you have a testing environment we can use to verify once it is in the Addon (in a pre-release) that this matches your expectations ?
If not it's ok I believe it should not be an issue.

Guilhem

**Comment by chadjefferies** [comment]
Thanks for the quick response!

> Don't use themeColor to indicate status.

Haha, oops. That's exactly what we use it for, but to be fair, we have other 3rd party integrations with Teams that use themeColor the same way so it seems like a quality addition.

We don't have a testing environment for Splunk unfortunately. The only way I can think to test it would be to install Splunk locally via Docker or something of that nature. I've never done that but would be willing to give it a try if you'd like.

**Comment by guilhemmarchand** [comment]
Hop that was easy @chadjefferies 

New version, 1.0.18, published in Splunk Base, provides the option to define the theme color to be used on a per alert basis.

Let me know if you have any issue.

**Comment by chadjefferies** [comment]
Thanks so much!
