### ISSUE TITLE
SHC replication fails, server.conf config missing in package

### ISSUE THREAD

**Issue by IceEyz** [guilhemmarchand/TA-ms-teams-alert-action#40]
Hi there,

It seems you've left server.conf in a temp folder during UCC migration:
https://github.com/guilhemmarchand/TA-ms-teams-alert-action/blob/master/temp/server.conf

This causes the app's configuration to not be replicated in a search head cluster anymore.

**Comment by guilhemmarchand** [comment]
Hi @IceEyz !

Ha damned thanks a lot for catching it, my bad indeed a mistake of mine during the migration ;-)

Will fix that anytime soon!
