### ISSUE TITLE
Not compatible with new Teams app on IOS

### ISSUE THREAD

**Issue by datkps11** [guilhemmarchand/TA-ms-teams-alert-action#49]
Recently, Teams app on IOS upgraded new version. So, this splunk app not compatible with new Teams app. Teams only show Tittle and not show message. Does any one have suggestions how to fix this?
Thanks

**Comment by guilhemmarchand** [comment]
Hi @datkps11 

Right, starting to review.

**Comment by larrys** [comment]
https://docs.microsoft.com/en-us/answers/questions/983587/ios-teams-app-doesn39t-display-webhook-message-con.html

We are also opening up a support ticket with MS on this, since it is not just this that is problematic, but other webhooks we use across our org.

**Comment by guilhemmarchand** [comment]
Thanks for sharing @larrys !
So it's a wide issue on the latest version of the app in IOS then when messages are formated in Markdown, wherever they come from

**Comment by larrys** [comment]
Latest update of teams app fixes this.
