### ISSUE TITLE
Only works for a single event

### ISSUE THREAD

**Issue by gravesb** [guilhemmarchand/TA-ms-teams-alert-action#6]
If there are multiple events in the result set for an alert, this ends up generating invalid json and the alert action fails to send.  Is this supposed to support multiple events or was it only meant to work for a single event in the result set?

For example, here is the json data generated from an alert on `index=_internal | stats count by source` (not a realistic alert, just something I used for testing purposes).
```
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"themeColor": "0076D7",
"summary": "Test 3",
"sections": [{
"activityTitle": "Test 3",
"activitySubtitle": "",
"facts": [
{
"name": "count",
"value": "2"
}
,{
"name": "source",
"value": "/opt/splunk/var/log/splunk/conf.log"
}
{
"name": "count",
"value": "4"
}
,{
"name": "source",
"value": "/opt/splunk/var/log/splunk/first_install.log"
}
{
"name": "count",
"value": "385"
}
,{
"name": "source",
"value": "/opt/splunk/var/log/splunk/health.log"
}
],
"markdown": false
}]
}
```

Each result has two fields, count and source.  Between fields for a single event, the comma is placed appropriately but the comma is missing between events.

**Comment by guilhemmarchand** [comment]
Hi @gravesb !

I think I get your point, therefore no the action is not meant to work with only a unique event but when you do, it assumes that you are grouping by and throttling on one or more keys within the alert.

**For example, I took you search (converted to tstats it's better !) and called that crazy alert, then:**

![image](https://user-images.githubusercontent.com/7503059/74290684-7ed3db00-4d2a-11ea-979b-6eb008b0a5d4.png)

Then once triggering, I get for each result (each line in your table) a message properly sent to the target, here I am using the Webhook site that is receiving the request:

![image](https://user-images.githubusercontent.com/7503059/74290750-b5115a80-4d2a-11ea-8a33-d480e77fd9c1.png)

![image](https://user-images.githubusercontent.com/7503059/74290763-c22e4980-4d2a-11ea-993a-187428280f10.png)

What happening if you are not splitting by is I agree not expected and should be managed properly, if a key x is found more that once, probably I should stop the iteration.

In the same time, you do want I believe to generate a message in the channel that is containing a huge amount of things, and each field must be unique entirely. (which is the purpose of the message card)

Let me know if it makes sense, but I can effectively take that search, have any number of results which will generate the same number of messages in your channel.

Guilhem

**Comment by gravesb** [comment]
Yup, that makes sense.  Changing the alert trigger to `For each result` seems like the best way to display the data in Teams as well.  Otherwise, it would be difficult to distinguish the events if they were all on the same card.  

I think a better error message in this scenario would certainly help matters.  An explicit error about too many events in the result set rather than the current json parser error.  Maybe also something in the documentation that mentions ensuring each alert only contains a single event.

**Comment by guilhemmarchand** [comment]
Agreed @gravesb 
Will be in next release.

**Comment by guilhemmarchand** [comment]
Hi @gravesb 

I actually carefully reviewed the code and the way the iteration though events was achieved, and it turns that you are right and this could effectively be working as expected in all cases.

I am publishing the version 1.0.5 which fixes it.

Thanks for opening this issue, much appreciated.

Guilhem

**Comment by guilhemmarchand** [comment]
Version 1.0.5 has been published in Splunk Base.

**Comment by gravesb** [comment]
Thanks for the quick turnaround on this.  For anyone else that comes across this, the updated functionality after the fix is to grab the first event in the list of events.  If you want something about each event sent to Teams, you still need to select `For each result` in the alert trigger configuration.
